/**
 * Disclaimer Utility Module
 * 
 * Provides standardized disclaimer text for all reports and outputs.
 * Ensures consistent legal protection across the application.
 */

// ============================================
// Disclaimer Texts
// ============================================

/**
 * Short disclaimer for inline use
 */
export const DISCLAIMER_SHORT =
    `PRELIMINARY DESIGN - NOT FOR CONSTRUCTION
Must be verified by a Registered Professional Engineer before use.`;

/**
 * Standard disclaimer for reports
 */
export const DISCLAIMER_STANDARD =
    `════════════════════════════════════════════════════════════════════
                         IMPORTANT NOTICE
════════════════════════════════════════════════════════════════════

This document is a PRELIMINARY DESIGN AID only.

BEFORE CONSTRUCTION, THE FOLLOWING MUST OCCUR:

  ✓ This design MUST be reviewed and certified by a Registered
    Professional Engineer (RPE) licensed in Papua New Guinea

  ✓ Building permit MUST be obtained from the PNG Building Board
    or relevant local authority

  ✓ All construction MUST be supervised by qualified personnel

  ✓ Site-specific conditions MUST be verified before construction

LIMITATIONS:

  • Calculations are based on assumed values and may not reflect
    actual site conditions

  • This software is NOT endorsed by the PNG Building Board

  • The developers accept NO LIABILITY for designs or construction
    based on this software

════════════════════════════════════════════════════════════════════
         BY PROCEEDING, ALL PARTIES ACCEPT THIS LIMITATION
════════════════════════════════════════════════════════════════════`;

/**
 * Full legal disclaimer for comprehensive reports
 */
export const DISCLAIMER_FULL =
    `════════════════════════════════════════════════════════════════════
                    LEGAL NOTICE AND DISCLAIMER
════════════════════════════════════════════════════════════════════

PURPOSE
-------
This document is generated by PNG Civil CAD, a DESIGN AID TOOL.
It is intended for PRELIMINARY DESIGN PURPOSES ONLY.

NO WARRANTY
-----------
This software and its outputs are provided "AS IS" without warranty
of any kind. The developers make NO guarantees regarding accuracy,
completeness, or suitability for any purpose.

REQUIRED PROFESSIONAL VERIFICATION
----------------------------------
ALL outputs from this software MUST be independently verified by
qualified professionals:

  1. STRUCTURAL DESIGNS must be reviewed, certified, and stamped
     by a Registered Professional Engineer (RPE) licensed to
     practice in Papua New Guinea.

  2. BUILDING PERMITS must be obtained from the PNG Building Board
     or relevant local authority before construction.

  3. ON-SITE INSPECTION must be conducted by qualified personnel
     during construction.

  4. LOCAL COMPLIANCE with all codes and regulations remains the
     sole responsibility of the licensed professionals.

LIMITATION OF LIABILITY
-----------------------
The authors, contributors, and distributors shall NOT be liable
for any damages, injuries, deaths, or losses arising from the use
of this software or its outputs, including but not limited to:

  • Structural failures or building collapses
  • Personal injury or loss of life
  • Property damage
  • Economic losses

ROLES AND RESPONSIBILITIES
--------------------------
• SOFTWARE DEVELOPERS: Provide calculations only; no guarantees
• SOFTWARE USERS: Engage licensed engineers; obtain permits
• PROFESSIONAL ENGINEERS: Verify and certify all designs
• BUILDERS: Work only from certified designs
• BUILDING OWNERS: Engage professionals; maintain structures

PNG BUILDING BOARD NOTICE
-------------------------
This software is NOT endorsed by the PNG Building Board.
All construction requires Building Board or local authority
approval before commencement.

ACCEPTANCE
----------
By using this software or documents generated by it, you
acknowledge that you have read, understood, and accept these
terms. If you do not agree, you must not use this software.

════════════════════════════════════════════════════════════════════`;

/**
 * Certification block to be filled by engineer
 */
export const ENGINEER_CERTIFICATION_BLOCK =
    `════════════════════════════════════════════════════════════════════
                   PROFESSIONAL ENGINEER CERTIFICATION
════════════════════════════════════════════════════════════════════

I, the undersigned Registered Professional Engineer, certify that:

  □ I have reviewed this preliminary design
  □ I have independently verified all calculations
  □ I have assessed site-specific conditions
  □ This design is suitable for the intended purpose
  □ This design complies with applicable PNG standards

Engineer Name:      _________________________________________

Registration No:    _________________________________________

Company:           _________________________________________

Signature:         _________________________________________

Date:              _________________________________________

Engineer's Stamp:






════════════════════════════════════════════════════════════════════`;

/**
 * Construction sequence specific disclaimer
 */
export const DISCLAIMER_CONSTRUCTION =
    `════════════════════════════════════════════════════════════════════
                     CONSTRUCTION SEQUENCE NOTICE
════════════════════════════════════════════════════════════════════

This construction sequence is GUIDANCE ONLY.

BEFORE USE:
  ✓ This sequence MUST be reviewed by the Engineer of Record
  ✓ Site-specific conditions MUST be assessed
  ✓ Actual weather and ground conditions may require adjustments
  ✓ All work must comply with approved, stamped drawings

THE BUILDER MUST:
  • Report any discrepancies to the Engineer before proceeding
  • Not proceed if conditions differ from those assumed
  • Maintain a site diary recording all activities
  • Stop work and seek guidance if uncertain

SAFETY REQUIREMENTS:
  • All workers must use appropriate PPE
  • Excavations must be properly shored
  • Formwork must be designed for concrete pressure
  • Never walk on unsupported roofing sheets

This guidance does NOT replace the need for:
  • Approved engineering drawings
  • Site supervision by qualified personnel
  • Compliance with PNG safety regulations

════════════════════════════════════════════════════════════════════`;

// ============================================
// Helper Functions
// ============================================

/**
 * Add disclaimer header to a report
 * @param {string} report - Original report text
 * @param {string} type - Disclaimer type: 'short', 'standard', 'full', 'construction'
 * @returns {string} Report with disclaimer prepended
 */
export function addDisclaimerHeader(report, type = 'standard') {
    const disclaimers = {
        short: DISCLAIMER_SHORT,
        standard: DISCLAIMER_STANDARD,
        full: DISCLAIMER_FULL,
        construction: DISCLAIMER_CONSTRUCTION,
    };

    const disclaimer = disclaimers[type] || disclaimers.standard;
    return `${disclaimer}\n\n${report}`;
}

/**
 * Add engineer certification block to a report
 * @param {string} report - Original report text
 * @returns {string} Report with certification block appended
 */
export function addCertificationBlock(report) {
    return `${report}\n\n${ENGINEER_CERTIFICATION_BLOCK}`;
}

/**
 * Add both disclaimer and certification to a report
 * @param {string} report - Original report text
 * @param {string} disclaimerType - Type of disclaimer
 * @returns {string} Complete report with disclaimer and certification
 */
export function addFullLegalWrapper(report, disclaimerType = 'standard') {
    return addCertificationBlock(addDisclaimerHeader(report, disclaimerType));
}

/**
 * Generate a document header with project info and disclaimer
 * @param {Object} project - Project details
 * @returns {string} Document header
 */
export function generateDocumentHeader(project) {
    const date = new Date().toLocaleDateString('en-GB', {
        day: 'numeric',
        month: 'long',
        year: 'numeric',
    });

    return `
PNG CIVIL CAD - DESIGN OUTPUT
Generated: ${date}
═══════════════════════════════════════════════════════════════════════

Project:    ${project.name || 'Untitled Project'}
Location:   ${project.province || 'Not Specified'}, Papua New Guinea
Reference:  ${project.reference || 'N/A'}

⚠️  PRELIMINARY DESIGN - REQUIRES PROFESSIONAL ENGINEER VERIFICATION  ⚠️

═══════════════════════════════════════════════════════════════════════
`;
}

// ============================================
// User Acceptance State
// ============================================

/**
 * Terms that user must accept before using the software
 */
export const USER_ACCEPTANCE_TERMS = [
    {
        id: 'understand-design-aid',
        text: 'I understand this software is a design aid, not a substitute for professional engineering judgment.',
        required: true,
    },
    {
        id: 'will-engage-engineer',
        text: 'I will ensure all outputs are reviewed and certified by a Registered Professional Engineer before construction.',
        required: true,
    },
    {
        id: 'will-obtain-permits',
        text: 'I will obtain all required permits and approvals from the PNG Building Board or local authority.',
        required: true,
    },
    {
        id: 'accept-no-liability',
        text: 'I accept that the developers bear no liability for designs or construction based on this software.',
        required: true,
    },
    {
        id: 'acknowledge-limitations',
        text: 'I acknowledge that calculations are based on assumptions that may not reflect actual site conditions.',
        required: true,
    },
];

/**
 * Check if user has accepted all required terms
 * @param {Object} acceptedTerms - Object with term IDs as keys and boolean values
 * @returns {{ accepted: boolean, missing: Array<string> }}
 */
export function checkUserAcceptance(acceptedTerms) {
    const missing = [];

    for (const term of USER_ACCEPTANCE_TERMS) {
        if (term.required && !acceptedTerms[term.id]) {
            missing.push(term.id);
        }
    }

    return {
        accepted: missing.length === 0,
        missing,
    };
}
